# Generated by Django 3.0.2 on 2020-01-10 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('Hospital_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Hospital_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uid', models.IntegerField()),
                ('Type', models.CharField(default='', max_length=20)),
                ('Hospital_id', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='dante.Hospital')),
            ],
            options={
                'unique_together': {('Uid', 'Hospital_id')},
            },
        ),
    ]
